# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pokémon Type Chart
email: your-email@domain.com
description: Pokémon Type Matchup Chart - shows how damage modifiers are applied when attacking and defending against Pokémon of different types
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

compress_html:
  clippings: "all"
  comments: "all"
  endings: "all"
  startings: [html, head, body]
